name: CI
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               gcc
               make
               clang
               libudev-dev
               libsdl2-dev
               libyaml-dev
               libsdl2-ttf-dev
               gcc-arm-none-eabi
               libnewlib-arm-none-eabi
               libfftw3-dev
    - name: Build libopencm3
      run: make -j4 -C firmware/libopencm3
    - name: Build firmware
      run: make -C firmware
    - name: Build host (gcc)
      run: make -BC host
    - name: Build host (clang)
      run: CC=clang make -BC host

  Code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               make
               cppcheck
               shellcheck
               clang-tools
               libudev-dev
               libsdl2-dev
               libyaml-dev
               libsdl2-ttf-dev
               libfftw3-dev
    - name: Shellcheck
      run: shellcheck run.sh
    - name: Clang scan-build host
      run: scan-build make -BC host/
    - name: Cppcheck host
      run: cppcheck --enable=warning,performance,portability,information --std=c11 host/
    - name: Cppcheck firmware
      run: cppcheck --enable=warning,performance,portability,information --std=c11 firmware/src/
